### ISSUE TITLE
Talep oluştur Enter tuşu  ile işlem

### ISSUE THREAD

**Issue by halitozdemir91** [limanmys/core#118]
kullanıcı rolündeki kişi ile talep oluştur ekranıunda talep oluştur dedikten sonra enter tuşu ile talebi oluştur diyorum. Enter tuşuna bir veya iki kere daha basarsam sistem donuyor.

**Comment by mertcelen** [comment]
Anladığımız kadarıyla bootstrap ile alakalı bir durum.
