### ISSUE TITLE
Tümünü kaldır fonksiyonu

### ISSUE THREAD

**Issue by halitozdemir91** [limanmys/core#119]
Sistem ayarları ekranından bir kullanıcı seçip açılan kullanıcı ayarlarındaki ekranlarda tüm tablarda bulunan tümünü kaldır işleminde herhangi bir fonksiyon çalışmamaktadır.
(versiyon --> 1.5.2 - 408)

**Comment by aliorhun** [comment]
İlgili tab'larda seçili objeler varsa "seçim" konusunda tümünü kaldırma fonksiyonu çalışıyor. Bu konuda küçük de olsa gif gönderebilir misiniz?

![ezgif-7-38351556a134](https://user-images.githubusercontent.com/260880/105447474-56b46200-5c85-11eb-83a5-a710625ca364.gif)

(versiyon --> 1.5.2 - 408)
