### ISSUE TITLE
smbafileshare eklentisinde gelen hata.

### ISSUE THREAD

**Issue by halitozdemir91** [limanmys/core#121]
içinde sambafileshare ile ilgili herhangi bir kurulum olmayan bir sunucuya bu eklentiyi eklediğimde
ilgili eklentinin ekranında aşağıdaki hatayı alıyorum.

Fatal error: Cannot redeclare index() (previously declared in /liman/extensions/sambafileshare/app/App.php(20) : eval()'d code:4) in /liman/extensions/sambafileshare/app/App.php(20) : eval()'d code on line 7

1.5.2 - 408

**Comment by mustafaakbel** [comment]
eklenti sürümü 0.18'e yükseltilmiştir
