### ISSUE TITLE
Terminal ekranı hatası

### ISSUE THREAD

**Issue by halitozdemir91** [limanmys/core#123]
Windows bir sunucu eklendikte sonra sunucu seçilip Terminal ekranına gidildiğinde Exception ekranı gözüküyor.

(v1.5.2-408)
![image](https://user-images.githubusercontent.com/6992716/105335014-97aa6900-5be8-11eb-8d75-1c3de1e4e5f1.png)

**Comment by mertcelen** [comment]
Terminal altyapimiz komple degisiyor, tamamlandiginda bu sorun cozulmus olacaktir.

**Comment by msongur** [comment]
Windows kapsam dışı tutulmuştur,
Linux serverlar için test edilmiştir.
