### ISSUE TITLE
USB Aktiviteleri ekranı Sonraki

### ISSUE THREAD

**Issue by halitozdemir91** [limanmys/core#124]
Envanter eklentisi içindeki USB aktiviteleri işleminde sonraki düğmesine listedeki sayıdan daha fazla tıklayınca liste boşalıyor.
Muhtemelen son sayfadayken sonraki düğmesini pasif yaparak çözülebilir.

Envanter 0.93 , v1.5.2. 408

**Comment by brnskn** [comment]
Envanter 1.0 sürümü şuan test ediliyor yeni sürümde bu sorun çözüldü
