### ISSUE TITLE
Sambafileshare eklentisi izin güncellenememesi

### ISSUE THREAD

**Issue by halitozdemir91** [limanmys/core#125]
Sambafileshare eklentisinde bir paylaşım seçip İzinleri güncelle düğmesi üzerindne güncelleme işlemi yapılmasına rağmen fonksiyon herhangi bir işlemi gerçekleştirmiyor.

v1.5.2.408 sambafileshare v0.19

**Comment by mustafaakbel** [comment]
Sürüm 0.22 ile çözülmüştür.
