### ISSUE TITLE
Ansible içeri dosya aktar

### ISSUE THREAD

**Issue by halitozdemir91** [limanmys/core#127]
Ansible eklentisinde içeriye bir dosya aktaracağız. Desteklenmeyen bir dosya seçtiğimde desteklenilmeyen dosya tipi kontrolü dosya yükleme tamamlandıktan sonra yapmak yerine direk ilk seçim esnasında yapmak daha doğru olacaktır.

v1.5.2.-408,  ansible v0.28

**Comment by mustafaakbel** [comment]
Sürüm 0.30 da dosya yükleme öncesi kontrol edilip uyarı verdirilmektedir.
