### ISSUE TITLE
Depo eklentisi adres silme

### ISSUE THREAD

**Issue by halitozdemir91** [limanmys/core#130]
Depo eklentisinde Adresler ekranına yeni bir satır eklendikten sonra güncelle veya silme yapmaya çalıştığında yapıldı oalrak uyarı gelse bile ekranda herhangi bir işlem gerçekleşmiyor.

v1.5.2.410 depo v0.45

**Comment by mustafaakbel** [comment]
Aynı durumu yakalayamadım. Eklenen depo adresini verebilir misiniz ?
