### ISSUE TITLE
Talep Admin tarafından silinirse açan tarafa reddedildi diye notification geliyor.

### ISSUE THREAD

**Issue by msongur** [limanmys/core#137]
Admin talebi kabul veya reddediğinde talep açan taraf yanlış bir mesaj alıyor

**Comment by brnskn** [comment]
Bu bilerek yapılıyor, talebin silinmesi kullanıcı için Reddedildi demektir aslında.

**Comment by brnskn** [comment]
liman-1.7-dev-1.7.0-340 sürümünde çözüldü

**Comment by msongur** [comment]
onaylandı.
