### ISSUE TITLE
Kaynak koddan derleme ve bağımlılıklar hakkında bilgi

### ISSUE THREAD

**Issue by milisarge** [limanmys/core#163]
Debian harici dağıtımlarda da kullanılabilmesi için kaynak koddan derleme ve bağımlılıklarına ilişkin bilgi içeren yardımcı belge mevcut mudur?

**Comment by aliorhun** [comment]
DEB paketi konusunda aşağıdaki kaynakları inceleyebilir ve debian harici dağıtımlarda da kullanılması için kaynak kod üzerinde neler yaptığımızı inceleyebilir ve bağımlılıklarımızı bulabilirsiniz:

- https://github.com/limanmys/core/blob/master/storage/create_deb.sh
- https://github.com/limanmys/core/tree/master/storage/build_tools

**Comment by milisarge** [comment]
teşekkür ederim, bunlar yeterli olacaktır.
