### ISSUE TITLE
Admin şifresi yenileme ekranında nokta işareti özel karakter sayılmıyor.

### ISSUE THREAD

**Issue by ahmetbicer** [limanmys/core#168]
Sistem tarafından otomatik oluşturulan admin şifresini değiştirirken nokta işareti ('.') özel karakterler arasında sayılmadığından parola geçersiz sayılıyor. `forcePasswordChange` fonksiyonundaki aşağıdaki regex sorunun kaynağı olabilir.

https://github.com/limanmys/core/blob/347fde9f6ece047e306427ab7c0cbb8ed12060fe/app/Http/Controllers/UserController.php#L401

**Comment by dogukanoksuz** [comment]
liman-1.8.1-436.deb ile duzeltildi. @ahmetbicer test edip issue kapatırsanız sevinirim.
![168_fix](https://user-images.githubusercontent.com/32539161/131350405-f27ae6b7-c064-4fea-b3df-35deac0fdf02.jpg)

**Comment by ahmetbicer** [comment]
Hızlı çözüm için teşekkürler. Yalnız şu [linkte](https://owasp.org/www-community/password-special-characters) belirtilen listeyle kullanılan regex'i karşılaştırdığımda hala eksik karakterler olduğunu görüyorum. Belki o listedeki karakterlerde eklenebilir. Onun dışında yapılan hotfix çalışıyor.
