### ISSUE TITLE
Bir eklenti sunucu terminalinden silindiğinde , liman arayüzünden silinmiyor 

### ISSUE THREAD

**Issue by velikrgl** [limanmys/core#171]
Bir eklenti oluşturduğumuzda eklenti  /liman/extensions bölümüne geliyor. Bu bölümdeki  herhangi bir eklenti sunucu terminalinden silindiğinde liman arayüzünde hala o eklenti varmış gibi görünüyor. Eklentiye tıkladığında ise 500(Server) hatası veriyor.

**Comment by dogukanoksuz** [comment]
Hata uyarısı handle edilmiştir.
