### ISSUE TITLE
[Improper Input Handling] [Liman CRASH] .env File Editing

### ISSUE THREAD

**Issue by oz9un** [limanmys/core#179]
#### For example, MAIL_USERNAME can be changed from "tweaks/mail settings":
![crash](https://user-images.githubusercontent.com/57866851/136758552-d9d1921a-651e-4eb5-a4ce-ac6646d81c7a.png)

#### Blank spaces in these fields (also in MAIL_PASSWORD); reflects to .env like that (no quotes!):
![crahs2](https://user-images.githubusercontent.com/57866851/136759559-fa6c1f62-3bb6-4e5b-a988-344b0348bc68.png)

**Comment by dogukanoksuz** [comment]
![fixed](https://user-images.githubusercontent.com/32539161/136901177-f77042dd-7c5f-422d-8f79-671454f94e81.png)

Hata düzeltildi.
