### ISSUE TITLE
Liman ID kopyalanma özelliği

### ISSUE THREAD

**Issue by aliorhun** [limanmys/core#180]
Liman ID gerektiği durumlarda kopyalanmada problem olduğu için kopyalanma özelliğinin eklenmesi uygun olabilir.

![Screenshot from 2021-10-29 14-21-54](https://user-images.githubusercontent.com/260880/139426443-c8486002-bb76-40d9-87f3-99e929c62c4b.png)

**Comment by dogukanoksuz** [comment]
1.8.3-RC 487 sürümü ile birlikte bu özellik eklenmiştir.

![image](https://user-images.githubusercontent.com/32539161/139629725-94ae9d36-5636-4337-99e8-658150973d44.png)
