### ISSUE TITLE
Mecvut Sunucu Sertifikalarının İnfo Bilgisi

### ISSUE THREAD

**Issue by duyguolmez** [limanmys/core#184]
`Ayarlar -> Sertifikalar` sayfsındaki yüklenmiş sertifika bilgilerinin ön izlenebilirliği mevcut sertifikayı kontrol etmek için gerekmektedir.
Aşağıdaki bilgiler modal ile gösterilebilir
![resim](https://user-images.githubusercontent.com/11041014/142573738-3bf3b6db-8676-45d6-b99e-6aba751a243f.png)

**Comment by dogukanoksuz** [comment]
1.9-RC1 sürümü ile özellik Liman'a eklenmiştir.
