### ISSUE TITLE
"Çok fazla oturum açma girişiminde bulundunuz" Refresh

### ISSUE THREAD

**Issue by duyguolmez** [limanmys/core#187]
Aşağıdaki şekilde bir hata alındığından terminal ekranından süreyi sıfırlamanın yöntemi dökümante edilebilir.

```
 Çok fazla oturum açma girişiminde bulundunuz. Lütfen 443 saniye içerisinde tekrar deneyiz. 
```

**Comment by brnskn** [comment]
O süreyi sıfırlamanın bir yolu yok. Liman’a ssh atabilen user’ın çok fazla oturum açma girişiminde bulunmadan şifreyi cli’dan sıfırlaması daha mantıklı bir senaryo.
