### ISSUE TITLE
Sistem Ayarlarının Rol Yönetimine Dahil Edilmesi

### ISSUE THREAD

**Issue by duyguolmez** [limanmys/core#188]
Ldap ile kullanım senaryolarında, yerel admin kullanıcılarla hiç giriş yapmadan sistem ayarları için bir rol grubu oluşturulamıyor.
Liman Admin Yetkileri şeklinde bir tab daha oluşturularak Sistem Ayarları da Rol Gruplarına dahil edilebilir.
![resim](https://user-images.githubusercontent.com/11041014/149736466-cce8a938-281f-404a-a03f-b6ec0b4929d8.png)

**Comment by brnskn** [comment]
Full yönetici yetkisi otomatize değil elle verilmesi gereken bir ayardır. Liman default administrator hesabından sadece bir kaç kişiye elle verilebilir. Bunu daha önceleri konuşup bu şekilde karar aldık. Birden fazla kişinin sistem ayarları ve diğer ayarlar gibi şeyleri değiştirebiliyor olması sistem güvenliği açısından sorun teşkil etmektedir.
