### ISSUE TITLE
Sunucu Bilgileri

### ISSUE THREAD

**Issue by duyguolmez** [limanmys/core#193]
Sunucularda anahtar kullanılıyor ise sunucu bilgileri kısmında giriş yapmış kullanıcı gösterilmelidir.
Whoami komutunun çıktısı gösterilebilir. (Windows powershell ve linux bash'de aynı şekilde çalışmakta)

![resim](https://user-images.githubusercontent.com/11041014/151939835-34a3d414-d958-45b0-bb4b-973500a633e2.png)

**Comment by dogukanoksuz** [comment]
![image](https://user-images.githubusercontent.com/32539161/151953933-22cc0efa-f232-4d9f-9a6a-86c2fb073545.png)

Özellik eklenmiştir
