### ISSUE TITLE
[BUG] Menüyü gizle yazısı silinmiyor

### ISSUE THREAD

**Issue by zekiahmetbayar** [limanmys/core#199]
**Hatayı açıklayın**
Liman MYS ekranında sol üstte bulunan menüyü gizle butonuna tıklandığında bilgi yazısı silinmiyor.

**Tekrarlamak için**
Bir kaç kez menüyü daraltıp açarak reproduce edilebilir.

**Beklenen davranış**
Her menüyü daraltıp açtıktan sonra ilgili bilgi yazısı silinmelidir.

**Ekran görüntüleri**
![image](https://user-images.githubusercontent.com/54356667/157397849-3dc6bee1-5e0e-47fa-8f2d-459048db026a.png)

**Sistem özellikleri**
- Liman Sürümü: 1.9 -549
- Sistem: Pardus 21.0

**Comment by dogukanoksuz** [comment]
Problem 1.9.2 sürümü ile giderilmiştir.
@zekiahmetbayar test edip kapatırsanız sevinirim.

**Comment by zekiahmetbayar** [comment]
Sorun yeni sürümde çözüldü, geri dönüş için teşekkürler.
