### ISSUE TITLE
Liman Rol Gruplarının Yeniden İsimlendirilebilmesi

### ISSUE THREAD

**Issue by duyguolmez** [limanmys/core#210]
Mevcut durumda rol grupları eklendikten sonra ismi düzenlenememekte.
Yanlış isimde bir rol grubu oluşturulursa silip yeniden oluşturulması gerekmekte ve içerisindeki bütün ayarlar kaybedilmekte.
Yeniden isimlendir özelliği eklenebilir.

**Comment by dogukanoksuz** [comment]
Özellik güncel sürüm ile eklenmiştir, testleri yapılmıştır.
