### ISSUE TITLE
[BUG] Rol gruplarında izin verilmiş eklenti silindiğinde liman 500 error'a düşüyor

### ISSUE THREAD

**Issue by zekiahmetbayar** [limanmys/core#212]
**Hatayı açıklayın**
Daha önceden eklenmiş bir eklentiyi rol gruplarından herhangi birine ekledikten sonra eğer eklenti silinirse, rol grubuna tıklandığında liman 500 server error hatası döndürüyor.

**Tekrarlamak için**
1. Yeni bir eklenti oluştur/ekle
2. Eklentiye rol grubunda izin tanımla
3. Eklentiyi sil
4. Rol grupları sekmesinde ilgili rol grubuna tıkla

**Beklenen davranış**
Eklenti silindiğinde rol grubundan da silinmelidir.

**Sistem özellikleri**
- Liman Sürümü: 1.10 632 dev
- Sistem: Ubuntu 20.04

**Comment by dogukanoksuz** [comment]
Senaryo test edilmiştir, hata gözlemlenememiştir. Problemsiz şekilde rol grubundan eklentinin silinebilmesi işlemi eklenti silme işlemine bağımlı olarak gerçekleşiyor.

Oluşma sebebi terminalden /liman/extensions sayfasına müdahaledendir. Veritabanı üzerinde bulunan db.json dosyası yolu bulunamadığından kaynaklanmıştır. Sistemden sağ tıklayıp sil denildiğinde bu yol temizlenmektedir.

**Comment by zekiahmetbayar** [comment]
Hata rol grubuna fonksiyon yetkisi eklendiğinden kaynaklanıyor.

Terminalden düzenlenmesi ile alakası yok aslında.

Tekrar kontrol edersen sevinirim.

**Comment by dogukanoksuz** [comment]
Çözüm gerçekleştirildi.
