### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by huseyinstif** [limanmys/core#228]
**Hatayı açıklayın**
Selamlar,
Eski commitlerinizde Slack File Upload Token 'Hardcoded' olarak durmaktadır. 
".github/workflows/main.yml" dosyası içerisinde  "https://slack.com/api/files.upload?token=" parametresinin karşısında token'ı görebilirsiniz. İlgili commiti kaldırmanızı veya token'ın geçerliliği var ise ilgili token'ı silmenizi tavsiye ederim.

İlgili Commitler:
https://github.com/limanmys/core/pull/86/commits/db81115b4658a3ca6d0ba14eaca2210eb8bb7909
https://github.com/limanmys/core/pull/74/commits/a4d8e2519e3706749c1d21a777a057126487f830#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R98

İyi Çalışmalar dilerim.

**Comment by dogukanoksuz** [comment]
Slacki yaklasık 3 senedir kullanmıyoruz.

Token zaten commit atıldıktan sonra direkt revoke edilmis.

Aciklab ekibi olarak ilginiz icin tesekkur eder, iyi calismalar dileriz.
