### ISSUE TITLE
Laravel Surumu

### ISSUE THREAD

**Issue by mertcelen** [limanmys/core#254]
Merhaba

https://github.com/limanmys/core/blob/62c3f62528bd75a17ea54592b468ff3f55687ddd/composer.json#L23

aktif laravel surumu epey eskide kalmis, guvenlik yamalarinin da coktan bittigini dusunursek mutlaka upgrade edilmesi gerek.

https://laravelversions.com/en

**Comment by dogukanoksuz** [comment]
2.1 sürümü ile Laravel 10.x sürümüne güncelleme yapıldı

```
liman@divergent:/liman/server$ php artisan --version
Laravel Framework 10.48.20
```

Q1 2025 tarihinde PHP sürümünün 8.3'e yükseltilmesi ve Laravel 12 güncellemesi planlandı.
